name: News Commentary Bot (Gemini 2.5 Pro)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  comment-news:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Debug - Check files
      run: |
        echo "=== Список файлов ==="
        ls -la
        echo "=== Проверка Facts.txt ==="
        if [ -f "Facts.txt" ]; then
          echo "✅ Facts.txt найден"
          echo "Размер: $(wc -c < Facts.txt) байт"
        else
          echo "❌ Facts.txt НЕ найден"
        fi
        echo "=== Проверка Python файла ==="
        if [ -f "news_bot.py" ]; then
          echo "✅ news_bot.py найден"
        else
          echo "❌ news_bot.py НЕ найден"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        echo "=== Установка зависимостей ==="
        pip install google-generativeai requests beautifulsoup4 lxml
        echo "=== Проверка установленных пакетов ==="
        pip list | grep -E "(google|requests|beautifulsoup4|lxml)"
        
    - name: Debug - Check environment
      run: |
        echo "=== Переменные окружения ==="
        if [ -n "$GEMINI_API_KEY" ]; then
          echo "✅ GEMINI_API_KEY установлен (длина: ${#GEMINI_API_KEY})"
        else
          echo "❌ GEMINI_API_KEY НЕ установлен"
        fi
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: Run news commentary
      id: run_bot
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "=== Запуск основного скрипта ==="
        python news_bot.py
        
        echo "=== Детальная проверка результатов ==="
        echo "Текущая папка: $(pwd)"
        echo "Содержимое корневой папки:"
        ls -la
        
        if [ -d "commentary" ]; then
          echo "✅ Папка commentary найдена"
          echo "Размер папки: $(du -sh commentary 2>/dev/null || echo 'Не удалось определить')"
          echo "Содержимое папки commentary:"
          ls -la commentary/ || echo "Ошибка чтения папки"
          echo "Количество файлов: $(ls commentary/ 2>/dev/null | wc -l)"
