- name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        echo "=== Проверка файлов перед коммитом ==="
        if [ -d "commentary" ]; then
          echo "✅ Папка commentary существует"
          echo "Содержимое:"
          ls -la commentary/ || echo "Папка пуста"
        else
          echo "❌ Папка commentary не существует"
        fi
        
        echo "=== Добавление файлов в Git ==="
        git add . || true
        
        echo "=== Проверка изменений ==="
        if git diff --staged --quiet; then
          echo "ℹ️ Нет новых файлов для коммита"
          exit 0
        else
          echo "✅ Найдены изменения, создаем коммит"
          git commit -m "Добавлен комментарий к новостям $(date)"
          git push
        fi
