name: News Commentary Bot (Gemini)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  comment-news:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug - Check files
      run: |
        echo "=== Список файлов ==="
        ls -la
        echo "=== Проверка Facts.txt ==="
        if [ -f "Facts.txt" ]; then
          echo "✅ Facts.txt найден"
          echo "Размер: $(wc -c < Facts.txt) байт"
        else
          echo "❌ Facts.txt НЕ найден"
        fi
        echo "=== Проверка Python файла ==="
        if [ -f "news_bot.py" ]; then
          echo "✅ news_bot.py найден"
        else
          echo "❌ news_bot.py НЕ найден"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
