name: News Commentary Bot (Gemini 2.5 Pro)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  comment-news:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Debug - Check files
      run: |
        echo "=== Список файлов ==="
        ls -la
        echo "=== Проверка Facts.txt ==="
        if [ -f "Facts.txt" ]; then
          echo "✅ Facts.txt найден"
          echo "Размер: $(wc -c < Facts.txt) байт"
        else
          echo "❌ Facts.txt НЕ найден"
        fi
        echo "=== Проверка Python файла ==="
        if [ -f "news_bot.py" ]; then
          echo "✅ news_bot.py найден"
        else
          echo "❌ news_bot.py НЕ найден"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        echo "=== Установка зависимостей ==="
        pip install google-generativeai requests beautifulsoup4 lxml
        echo "=== Проверка установленных пакетов ==="
        pip list | grep -E "(google|requests|beautifulsoup4|lxml)"
        
    - name: Debug - Check environment
      run: |
        echo "=== Переменные окружения ==="
        if [ -n "$GEMINI_API_KEY" ]; then
          echo "✅ GEMINI_API_KEY установлен (длина: ${#GEMINI_API_KEY})"
        else
          echo "❌ GEMINI_API_KEY НЕ установлен"
        fi
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: Run news commentary
      id: run_bot
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "=== Запуск основного скрипта ==="
        python news_bot.py
        
        echo "=== Детальная проверка результатов ==="
        echo "Текущая папка: $(pwd)"
        echo "Содержимое корневой папки:"
        ls -la
        
        if [ -d "commentary" ]; then
          echo "✅ Папка commentary найдена"
          echo "Размер папки: $(du -sh commentary 2>/dev/null || echo 'Не удалось определить')"
          echo "Содержимое папки commentary:"
          ls -la commentary/ || echo "Ошибка чтения папки"
          echo "Количество файлов: $(ls commentary/ 2>/dev/null | wc -l)"
          
          if [ "$(ls -A commentary 2>/dev/null)" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
            echo "✅ Файлы найдены в папке commentary"
            
            for file in commentary/*; do
              if [ -f "$file" ]; then
                echo "=== Содержимое $file (первые 5 строк) ==="
                head -5 "$file" || echo "Не удалось прочитать файл"
                echo "=========================="
              fi
            done
          else
            echo "success=false" >> $GITHUB_OUTPUT
            echo "❌ Папка commentary пуста"
          fi
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "❌ Папка commentary не существует"
        fi
        
        echo "=== Проверка статуса выхода Python скрипта ==="
        echo "Exit code: $?"
      
    - name: Commit and push results
      if: steps.run_bot.outputs.success == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Добавляем все файлы в commentary
        git add commentary/
        
        # Проверяем есть ли новые или измененные файлы
        if git diff --staged --quiet; then
          echo "⚠️ Нет новых изменений для коммита"
          echo "Возможно файлы уже существуют с тем же содержимым"
          
          # Форсированно пересоздаем файлы с новым временем
          timestamp=$(date +"%Y%m%d_%H%M%S")
          echo "🔄 Создаем файлы с новой меткой времени: $timestamp"
          
          # Запускаем скрипт еще раз для создания файлов с новым временем
          python -c "
import os
from datetime import datetime
timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
print(f'Создаем тестовый файл с timestamp: {timestamp}')
os.makedirs('commentary', exist_ok=True)
with open(f'commentary/test_{timestamp}.txt', 'w') as f:
    f.write(f'Test file created at {timestamp}')
"
          git add commentary/
        fi
        
        # Пробуем коммитить снова
        if ! git diff --staged --quiet; then
          git commit -m "Обновлен комментарий к новостям $(date '+%d.%m.%Y %H:%M')"
          git push origin main
          echo "✅ Изменения успешно закоммичены"
        else
          echo "ℹ️ Все файлы актуальны, коммит не требуется"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Report if no files created
      if: steps.run_bot.outputs.success != 'true'
      run: |
        echo "⚠️ Скрипт завершился, но файлы не были созданы"
        echo "Возможные причины:"
        echo "- Ошибка получения новостей"
        echo "- Ошибка API Gemini" 
        echo "- Ошибка сохранения файлов"
